<#
.SYNOPSIS
  Kills KiCad if running, runs "ergogen .\ergogen\", and if successful opens output/pcbs/left.kicad_pcb

.USAGE
  .\run-ergogen-and-open.ps1

generated by chatgpt
#>

[CmdletBinding()]
param()

# --- Configuration ---
$ergogenCommand = "ergogen .\ergogen\"      # The command to run
$pcbPath = "output\pcbs\left.kicad_pcb"
$kicadProcesses = @('kicad', 'pcbnew')      # Common KiCad processes

function Write-Info { Write-Host "[*] $($args -join ' ')" -ForegroundColor Cyan }
function Write-Ok   { Write-Host "[+] $($args -join ' ')" -ForegroundColor Green }
function Write-Err  { Write-Host "[-] $($args -join ' ')" -ForegroundColor Red }

try {
    # --- Kill KiCad if it's open ---
    Write-Info "Checking for KiCad processes..."
    $found = Get-Process -Name $kicadProcesses -ErrorAction SilentlyContinue
    if ($found) {
        foreach ($p in $found) {
            Write-Info "Killing $($p.ProcessName) (PID $($p.Id))..."
            Stop-Process -Id $p.Id -Force -ErrorAction SilentlyContinue
        }
        Write-Ok "KiCad processes terminated."
    } else {
        Write-Info "No KiCad processes found."
    }

    # --- Run ergogen ---
    Write-Info "Running command: $ergogenCommand"
    $ergogen = Start-Process "powershell" -ArgumentList "-NoProfile", "-Command", $ergogenCommand `
        -NoNewWindow -Wait -PassThru

    if ($ergogen.ExitCode -ne 0) {
        throw "ergogen failed with exit code $($ergogen.ExitCode)"
    }

    # --- Open the generated PCB file ---
    if (Test-Path $pcbPath) {
        Write-Ok "Opening PCB: $pcbPath"
        Start-Process $pcbPath
    } else {
        throw "PCB file not found: $pcbPath"
    }

    Write-Ok "Done."
}
catch {
    Write-Err $_.Exception.Message
    exit 1
}
