<#
.SYNOPSIS
  Runs "ergogen .\ergogen\" and if successful opens output/pcbs/left.kicad_pcb.
  Optionally kills KiCad if running before starting.

.USAGE
  .\run-ergogen-and-open.ps1
  (Runs ergogen and opens PCB without killing KiCad)

  .\run-ergogen-and-open.ps1 -KillKiCad
  (Kills KiCad, then runs ergogen and opens PCB)

.PARAMETER KillKiCad
  If specified, the script will find and stop any running KiCad processes
  ('kicad', 'pcbnew') before running ergogen.

script generated by chatgpt & Gemini
#>

[CmdletBinding()]
param(
    # If this switch is provided (e.g., -KillKiCad), the script will kill KiCad processes.
    [switch]$KillKiCad
)

# --- Configuration ---
$ergogenCommand = "ergogen .\ergogen\"      # The command to run
$pcbPath = "output\pcbs\left.kicad_pcb"
$kicadProcesses = @('kicad', 'pcbnew')      # Common KiCad processes

function Write-Info { Write-Host "[*] $($args -join ' ')" -ForegroundColor Cyan }
function Write-Ok   { Write-Host "[+] $($args -join ' ')" -ForegroundColor Green }
function Write-Err  { Write-Host "[-] $($args -join ' ')" -ForegroundColor Red }

try {
    # --- Kill KiCad if it's open (and -KillKiCad was specified) ---
    if ($KillKiCad) {
        Write-Info "Checking for KiCad processes..."
        $found = Get-Process -Name $kicadProcesses -ErrorAction SilentlyContinue
        if ($found) {
            foreach ($p in $found) {
                Write-Info "Killing $($p.ProcessName) (PID $($p.Id))..."
                Stop-Process -Id $p.Id -Force -ErrorAction SilentlyContinue
            }
            Write-Ok "KiCad processes terminated."
        } else {
            Write-Info "No KiCad processes found."
        }
    } else {
        Write-Info "Skipping KiCad process check (no -KillKiCad switch provided)."
    }

    # --- Run ergogen ---
    Write-Info "Running command: $ergogenCommand"
    # Using Invoke-Expression for simpler command execution that shows output directly
    Invoke-Expression $ergogenCommand
    
    # Check the exit code of the last command
    if ($LASTEXITCODE -ne 0) {
        throw "ergogen failed with exit code $LASTEXITCODE"
    }

    # --- Open the generated PCB file ---
    if (Test-Path $pcbPath) {
        Write-Ok "Opening PCB: $pcbPath"
        Start-Process $pcbPath
    } else {
        throw "PCB file not found: $pcbPath"
    }

    Write-Ok "Done."
}
catch {
    Write-Err $_.Exception.Message
    exit 1
}